# Generated by Django 6.0.2 on 2026-02-23 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='unique_lesson_progree',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('student', 'lesson'), name='unique_lesson_progress'),
        ),
    ]
